{"name": "Login user with incorrect auth data: {'password': '1qaz.2wsx.3edc'}", "status": "passed", "steps": [{"name": "Login user", "status": "passed", "parameters": [{"name": "email", "value": "None"}, {"name": "password", "value": "'1qaz.2wsx.3edc'"}], "start": 1724244967437, "stop": 1724244967856}], "parameters": [{"name": "auth_params", "value": "{'password': '1qaz.2wsx.3edc'}"}], "start": 1724244967437, "stop": 1724244967856, "uuid": "cef5a489-7d4a-4cd3-aec4-82d582a7ff5f", "historyId": "264a16d3c8c1b1b81320190d97515ac6", "testCaseId": "4e38b3e3ebd6f6ecfb061015dba24b00", "fullName": "tests.test_auth.TestAuthLogin#test_login_wrong_data_unsuccessful", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthLogin"}, {"name": "host", "value": "opeshko"}, {"name": "thread", "value": "43448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}