{"name": "Login user with incorrect auth data: {'email': 'new_email_123@test.host'}", "status": "passed", "steps": [{"name": "Login user", "status": "passed", "parameters": [{"name": "email", "value": "'new_email_123@test.host'"}, {"name": "password", "value": "None"}], "start": 1724244967079, "stop": 1724244967432}], "parameters": [{"name": "auth_params", "value": "{'email': 'new_email_123@test.host'}"}], "start": 1724244967079, "stop": 1724244967432, "uuid": "1cbead0a-f963-4235-8841-161dae412ae0", "historyId": "81634c65128942b463fdd969a09d0c23", "testCaseId": "4e38b3e3ebd6f6ecfb061015dba24b00", "fullName": "tests.test_auth.TestAuthLogin#test_login_wrong_data_unsuccessful", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthLogin"}, {"name": "host", "value": "opeshko"}, {"name": "thread", "value": "43448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}